// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://maven.pkg.jetbrains.space/kotlin/p/kotlin/eap" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.0-alpha07'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.20-Beta2"
        classpath "org.jetbrains.kotlin:kotlin-serialization:2.3.20-Beta2"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.3.20-Beta2"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.3.5"
        classpath "dev.detekt:detekt-gradle-plugin:2.0.0-alpha.2"
        classpath "com.google.gms:google-services:4.4.2"
    }
    configurations.all {
        resolutionStrategy {
            force libs.jose4j
            force libs.jdom2
            force libs.apache.commons.lang3
            force libs.apache.httpclient
            force libs.netty.codec.http
            force libs.netty.codec
            force libs.netty.codec.http2
            force libs.netty.common
            force libs.netty.handler
            force libs.netty.resolver
            force libs.netty.transport
            force libs.netty.buffer
        }
    }
}

plugins {
    id "nl.littlerobots.version-catalog-update" version "1.0.1"
}

subprojects {
    def applyDetekt = {
        apply plugin: "dev.detekt"
        detekt {
            autoCorrect = true
            parallel = true
            buildUponDefaultConfig = true
        }
        dependencies {
            detektPlugins "dev.detekt:detekt-rules-ktlint-wrapper:2.0.0-alpha.2"
        }
    }

    plugins.withId("com.android.application") { applyDetekt() }
    plugins.withId("com.android.library") { applyDetekt() }
    plugins.withId("org.jetbrains.kotlin.jvm") { applyDetekt() }
    plugins.withId("org.jetbrains.kotlin.android") { applyDetekt() }

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://maven.pkg.jetbrains.space/kotlin/p/kotlin/eap" }
        maven { url = "https://api.xposed.info/" }
        maven { url = "https://jitpack.io" }
        maven {
            url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
