// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        mavenCentral() // add repository
        maven { url = "https://maven.pkg.jetbrains.space/kotlin/p/kotlin/eap" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.1.0-alpha07'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.20-Beta2"
        classpath "org.jetbrains.kotlin:kotlin-serialization:2.3.20-Beta2"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.3.20-Beta2"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.3.5"
    }
    configurations.all {
        resolutionStrategy {
            force 'org.bitbucket.b_c:jose4j:0.9.6'
            force 'org.jdom:jdom2:2.0.6.1'
            force 'org.apache.commons:commons-lang3:3.17.0'
            force 'org.apache.httpcomponents:httpclient:4.5.13'
            force 'io.netty:netty-codec-http:4.1.129.Final'
            force 'io.netty:netty-codec:4.1.129.Final'
            force 'io.netty:netty-codec-http2:4.1.129.Final'
            force 'io.netty:netty-common:4.1.129.Final'
            force 'io.netty:netty-handler:4.1.129.Final'
            force 'io.netty:netty-resolver:4.1.129.Final'
            force 'io.netty:netty-transport:4.1.129.Final'
            force 'io.netty:netty-buffer:4.1.129.Final'
        }
    }
}

plugins {
    id "nl.littlerobots.version-catalog-update" version "1.0.1"
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url = "https://maven.pkg.jetbrains.space/kotlin/p/kotlin/eap" }
        maven { url = "https://api.xposed.info/" }
        maven { url = "https://jitpack.io" }
        maven {
            url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
